[package]
name = "caliptra-fips"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caliptra-error = { version = "0.1.0", path = "../../error" }
caliptra_common = { version = "0.1.0", path = ".." }


